queue_rules:
  - name: default
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label!=work-in-progress
    actions:
      queue:
        name: default
