name: Validate Codeowners
on:
  workflow_dispatch:

  pull_request:

jobs:
  validate-codeowners:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout source code at current commit"
      uses: actions/checkout@v2
    - uses: mszostok/codeowners-validator@v0.7.5-rc1
      if: github.event.pull_request.head.repo.full_name == github.repository
      name: "Full check of CODEOWNERS"
      with:
        checks: "files,syntax,owners,duppatterns"
        # GitHub access token is required only if the `owners` check is enabled
        github_app_id: ${{ secrets.GH_APP_ID }}
        github_app_installation_id: ${{ secrets.GH_INSTALLATION_ID }}
        github_app_private_key: ${{ secrets.GH_PRIVATE_KEY }}
    - uses: mszostok/codeowners-validator@v0.5.0
      if: github.event.pull_request.head.repo.full_name != github.repository
      name: "Syntax check of CODEOWNERS"
      with:
        checks: "syntax,duppatterns"